import { StyleSheet } from 'react-native';

const Design = StyleSheet.create({
    //LOGIN SCREEN STYLESHEET
    body: {
        flex: 1,
    },
    topv: {
        width: '100%',
        height: '85%',
        alignItems: 'center',
    },
    lh1: {
        alignSelf: 'center',
        fontSize: 36,
        fontWeight: '700',
        marginTop: 50,
        marginBottom: 30,
        color: '#ffffff',
        fontFamily: 'inter',
    },
    lh2: {
        alignSelf: 'center',
        fontSize: 20,
        fontWeight: 'bold',
        fontFamily: 'inter',
        color: 'white',
    },
    logo: {
        alignSelf: 'center',
        marginTop: 30,
        height: 125,
        width: 122,
    },
    imgbg: {
        height: '100%',
        width: '100%',
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        overflow: 'hidden',
    },
    input: {
        alignSelf: 'center',
        marginVertical: 20,
        borderRadius: 7,
        borderWidth: 2,
        borderColor: '#ffffff',
        width: '90%',
        fontFamily: 'inter',
        fontWeight: '400',
        fontSize: 20,
        lineHeight: 29,
        color: 'white',
        paddingLeft: 15,
    },
    inhead: {
        marginLeft: 20,
        fontSize: 20,
        fontStyle: 'normal',
        fontWeight: '600',
        lineHeight: 29,
        fontFamily: 'inter',
        color: 'white',
    },
    loginbtn: {
        width: '90%',
        marginVertical: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#6B1FB7',
        alignSelf: 'center',
        height: 48,
        borderRadius: 5,
        marginTop: 10,
    },
    logintxt: {
        color: '#fff',
        fontWeight: '500',
        fontSize: 20,
        alignSelf: 'center',
        marginHorizontal: 17,
    },
    rarrow: {
        height: 32,
        width: 32,
        alignSelf: 'center',
        marginRight: 15,
    },
    logdots: {
        height: 14,
        width: 57,
        alignSelf: 'center',
        marginRight: 15,
    },
    forgot: {
        fontSize: 14,
        fontWeight: '500',
        alignSelf: 'flex-end',
        marginHorizontal: 30,
        marginTop: 3,
    },
    prereg: {
        fontSize: 20,
        color: '#000',
    },
    register: {
        alignSelf: 'center',
        fontSize: 20,
        color: '#1F37B7',
    },
    b1: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
    },
    b2: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    // REGISTER SCREEN STYLESHEET
    regtop: {
        height: '15%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    registerbg: {
        height: '100%',
        width: '100%',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        overflow: 'hidden',
        paddingTop: 30,
    },
    bottomv: {
        height: '100%',
        width: '100%',
        alignSelf: 'center',
    },
    rh1: {
        fontSize: 32,
        color: '#fff',
        lineHeight: 39,
        fontWeight: '400',
        marginLeft: 20,
        marginBottom: 20,
    },
    already: {
        fontSize: 20,
        color: '#000',
        marginLeft: 30,
    },
    tologin: {
        marginTop: 10,
        marginLeft: 20,
        flexDirection: 'row',
    },
    larrow: {
        height: 40,
        width: 40,
    },
    logdots2: {
        height: 14,
        width: 57,
        alignSelf: 'center',
        marginLeft: 15,
    },
    logintxt2: {
        color: '#fff',
        fontWeight: '500',
        fontSize: 20,
        alignSelf: 'center',
        marginHorizontal: 10,
    },
});
export default Design;
